#!/bin/bash
# This script was made by `goferito` on Github.
# Some cleanup by Luke.

[ -z "$1" ] && echo "No direction provided" && exit 1

moveChoice() {
  swaymsg resize "$1" "$2" 4 ppt
  swaymsg resize "$3" "$4" 4 ppt
}

case $1 in
  up)
    moveChoice grow up shrink down
    ;;
  down)
    moveChoice shrink up grow down
    ;;
  left)
    moveChoice shrink right grow left
    ;;
  right)
    moveChoice grow right shrink left
    ;;
esac

exit 0
